// This file will be generated by flutterfire configure
// You need to run: flutterfire configure
// This will create the actual Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRFKALOW3-wNSRwshU03huqS-XGveaDo',
    appId: '1:606413814584:web:your-web-app-id',
    messagingSenderId: '606413814584',
    projectId: 'babelly-terrahacks',
    authDomain: 'babelly-terrahacks.firebaseapp.com',
    storageBucket: 'babelly-terrahacks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRFKALOW3-wNSRwshU03huqS-XGveaDo',
    appId: '1:606413814584:android:19430992301d86cb4ddfcd',
    messagingSenderId: '606413814584',
    projectId: 'babelly-terrahacks',
    storageBucket: 'babelly-terrahacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRFKALOW3-wNSRwshU03huqS-XGveaDo',
    appId: '1:606413814584:ios:your-ios-app-id',
    messagingSenderId: '606413814584',
    projectId: 'babelly-terrahacks',
    storageBucket: 'babelly-terrahacks.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.interactingTom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdRFKALOW3-wNSRwshU03huqS-XGveaDo',
    appId: '1:606413814584:macos:your-macos-app-id',
    messagingSenderId: '606413814584',
    projectId: 'babelly-terrahacks',
    storageBucket: 'babelly-terrahacks.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.interactingTom',
  );
} 